<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Theme Contentmodifier - core_renderer class file
 *
 * @package    theme_contentmodifier
 * @copyright  2022 Bernhard Strehl <moodle@software.bernhard-strehl.de>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
namespace theme_contentmodifier\output;


defined('MOODLE_INTERNAL') || die;


/**
 * A custom renderer. It offers the possibility to extend the main_content 
 * generated by Moodle with any arbitrary html-code.
 * Plugins / other themes can implement "class core_modifier extends \core_modifier_base"
 * and thus extend /  modify the main_content
 * 
 *
 * @package    theme_contentmodifier
 * @copyright   2022 Bernhard Strehl <moodle@software.bernhard-strehl.de>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class core_renderer extends \theme_boost\output\core_renderer
{

    /**
     * extends function main_content() in file lib/outputrenderers.php
     * needed to add content to the main_content
     * 
     * this html is then printed in file theme/boost/templates/drawers.mustache
     * @return string HTML fragment.
     */
    public function main_content()
    {

        global $COURSE;
        $courseid = $COURSE->id;

        $contextid = \optional_param('id', null, PARAM_INT);

        $maincontent = parent::main_content();

        if (!$contextid || !$courseid) {   //abbruch - wir sind in nem iframe, 
            //schauen gerade keinen content an, content ohne kurs etc.
            return $maincontent;
        }

        //geht nicht über autoload, aber nicht schlimm
        require(__DIR__ . '/outputmodifiersfactories.php');
        $modifierfactory = new \overridden_outputmodifiers_factory();

        $pagemodifiers = $modifierfactory->get_modifiers();
        foreach ($pagemodifiers as $pmod) {
            $pmod->append_content_to_main($maincontent);
            $pmod->modify_main_content($maincontent);
        }

        return $maincontent;
    }
}
